#!/bin/sh
BG=$(xrdb -query | grep st.background | awk '{print$2}')
FG=$(xrdb -query | grep st.foreground | awk '{print$2}')
ACCENT=$(xrdb -query | grep st.color2 | awk '{print$2}')
BAR_HEIGHT={{{bar_height}}}

bemenu-run -p "run" \
	   -i \
	   -H $BAR_HEIGHT \
	   --fn "{{{font_name}}} {{{font_size}}}" \
	   --tb "$BG" \
	   --fb "$BG" \
	   --nb "$BG" \
	   --hb "$BG" \
	   --sb "$BG" \
	   --ab "$BG" \
	   --tf "$ACCENT" \
	   --ff "$FG" \
	   --nf "$FG" \
	   --hf "$ACCENT" \
	   --sf "$FG" \
	   --af "$FG" \
	   --cf "$BG" \
	   --cb "$BG" 
