#!/bin/sh
# this is how u output json kid

REFRESH_TIME=3

FG=$(xrdb -query | grep st.foreground | awk '{print$2}')
BG=$(xrdb -query | grep st.background | awk '{print$2}')
GREEN=$(xrdb -query | grep st.color2 | head -n 1 | awk '{print$2}')
YELLOW=$(xrdb -query | grep st.color3 | awk '{print$2}')
RED=$(xrdb -query | grep st.color1 | head -n 1 | awk '{print$2}')
BLUE=$(xrdb -query | grep st.color4 | head -n 1 | awk  '{print$2}')

echo '{"version":1}'
echo '['
echo '[]'

while true
do
    date=$(date +'%H:%M')

    volumeLevel=$(pactl get-sink-volume @DEFAULT_SINK@ | head -n 1 | awk '{print $5}' | sed 's/%.*//')
    volumeMute=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')

    if [ $volumeMute = "" ]; then
	volumeStatus="MUTE"
	volumeColor=$YELLOW
    else
	volumeStatus=$volumeLevel
	if [ $volumeLevel -gt 80 ]; then
	    volumeColor=$RED
	else
	    volumeColor=$GREEN
	fi
    fi

    if [ -d /sys/class/power_supply/BAT0 ]; then
	batteryLevel=$(cat /sys/class/power_supply/BAT0/capacity)
	batteryStatus=$(cat /sys/class/power_supply/BAT0/status)
	if [ $batteryStatus = "Charging" ]; then
	    batteryColor=$YELLOW
	elif [ $batteryLevel -lt 25 ]; then
	    batteryColor=$RED
	else
	    batteryColor=$BLUE
	fi	    
    else
	batteryLevel="No Battery"
	batteryColor=$BLUE
    fi

    echo -n ',['
    echo -n "{\"name\":\"battery\",\"markup\":\"pango\",\"full_text\":\"Bat: <span foreground='$batteryColor'>$batteryLevel</span>\"},"
    echo -n "{\"name\":\"volume\",\"markup\":\"pango\",\"full_text\":\"Volume: <span foreground='$volumeColor'>$volumeStatus</span>\"},"
    echo -n "{\"name\":\"time\",\"markup\":\"pango\",\"full_text\":\"<b>$date</b> \"}"
    echo -n ']'

    sleep $REFRESH_TIME
    echo

done
