require("core.plugconfig.colors")
require("core.plugconfig.lualine")
require("core.plugconfig.telescope")
require("core.plugconfig.undotree")
require("core.plugconfig.treesitter")
require("core.plugconfig.lsp")
