vim.opt.errorbells = false
vim.opt.linebreak = true
vim.opt.relativenumber = true
vim.opt.termguicolors = true
vim.opt.smartcase = true
-- vim.opt.undodir = '~/.cache/vimundo'
-- vim.opt.undofile = true
vim.opt.autoindent = true
vim.opt.expandtab = trye
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
